/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sgi.frame;

import br.com.sgi.bean.NotaFiscal;
import br.com.sgi.dao.NotaFiscalDAO;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.openswing.swing.mdi.client.InternalFrame;
import org.openswing.swing.mdi.client.MDIFrame;
import org.openswing.swing.util.client.ClientSettings;

/**
 *
 * @author jairosilva
 */
public class IntegrarPedidoVenda extends InternalFrame {

    private boolean addNewReg;
    private boolean showMsgErros;
    private IntegrarPesosRegistrar veioCampo;
    private NotaFiscalDAO notafiscalDAO;
    private List<NotaFiscal> lstNotaFiscal = new ArrayList<NotaFiscal>();

    public IntegrarPedidoVenda() {
        try {
            initComponents();
            setTitle(ClientSettings.getInstance().getResources().getResource("Pedidos de Compra"));
            this.setSize(800, 500);
            this.notafiscalDAO = new NotaFiscalDAO();

            getListar("", "");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void setRecebePalavra(IntegrarPesosRegistrar veioInput) {
        btnPesquisar.setEnabled(false);
        this.veioCampo = veioInput;
        return;
    }

    public void getListar(String PESQUISA_POR, String PESQUISA) throws SQLException, Exception {
        if (PESQUISA_POR.equals("NFV")) {
            lstNotaFiscal = this.notafiscalDAO.getNotaFiscais(PESQUISA_POR, PESQUISA);
            if (lstNotaFiscal != null) {
                carregarTabela();
            }
        } else {

        }

    }

    public void carregarTabela() throws Exception {
        jTableDefeitos.setRowHeight(32);
        DefaultTableModel modeloCarga = (DefaultTableModel) jTableDefeitos.getModel();
        modeloCarga.setNumRows(0);

        for (NotaFiscal nf : lstNotaFiscal) {
            Object[] linha = new Object[15];

            // popula as colunas
            linha[1] = nf.getNotafiscal();
            linha[2] = nf.getCodigocliente();
            linha[3] = nf.getCliente().getNome();
            linha[4] = nf.getTransportadora();
            linha[5] = nf.getNomeTransportadora();
            linha[6] = nf.getPedido();
            linha[7] = nf.getPesoLiquido();
            linha[8] = false;
            linha[9] = nf.getEmpresa();
            linha[10] = nf.getFilial();

            modeloCarga.addRow(linha);
        }

    }

    void recebendoTransportes(String codigoTransportadora, String nomeTransportadora) throws Exception {
        txtPesquisar.setText(codigoTransportadora);
        getListar("NFV", " and nfv.codtra in (" + txtPesquisar.getText() + ")");
        txtPesquisar.requestFocus();

    }

    public void selecionarRange() throws SQLException, Exception {
        btnPesquisar.setEnabled(false);
        String selecionar = "";
        txtNomeSelecao.setText(selecionar);
        if (jTableDefeitos.getRowCount() > 0) {
            for (int i = 0; i < jTableDefeitos.getRowCount(); i++) {
                if ((Boolean) jTableDefeitos.getValueAt(i, 8)) {
                    selecionar += (jTableDefeitos.getValueAt(i, 1).toString() + ",");
                    btnPesquisar.setEnabled(true);
                }
            }
            int tam = selecionar.length();
            selecionar = selecionar.substring(0, tam - 1);
            txtNomeSelecao.setText(selecionar);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpOpt = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDefeitos = new javax.swing.JTable();
        txtPesquisar = new org.openswing.swing.client.TextControl();
        txtCodigoSelecionado = new org.openswing.swing.client.TextControl();
        txtNomeSelecao = new org.openswing.swing.client.TextControl();
        optNota = new javax.swing.JRadioButton();
        optPedido = new javax.swing.JRadioButton();
        btnTransportadora = new javax.swing.JButton();
        optTransportadora = new javax.swing.JRadioButton();
        txtFilial = new org.openswing.swing.client.TextControl();
        txtEmpresa = new org.openswing.swing.client.TextControl();
        optCli = new javax.swing.JRadioButton();
        optCli1 = new javax.swing.JRadioButton();
        btnPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ordem de Compras");
        setPreferredSize(new java.awt.Dimension(599, 188));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableDefeitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Numero", "Cliente", "Nome", "Transp.", "Nome ", "Pedido", "Peso", "Selecionar", "Empresa", "Filial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDefeitos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDefeitosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDefeitos);
        if (jTableDefeitos.getColumnModel().getColumnCount() > 0) {
            jTableDefeitos.getColumnModel().getColumn(0).setMinWidth(50);
            jTableDefeitos.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableDefeitos.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableDefeitos.getColumnModel().getColumn(1).setMinWidth(100);
            jTableDefeitos.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableDefeitos.getColumnModel().getColumn(1).setMaxWidth(100);
            jTableDefeitos.getColumnModel().getColumn(2).setMinWidth(100);
            jTableDefeitos.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableDefeitos.getColumnModel().getColumn(2).setMaxWidth(100);
            jTableDefeitos.getColumnModel().getColumn(4).setMinWidth(100);
            jTableDefeitos.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableDefeitos.getColumnModel().getColumn(4).setMaxWidth(100);
            jTableDefeitos.getColumnModel().getColumn(6).setMinWidth(100);
            jTableDefeitos.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTableDefeitos.getColumnModel().getColumn(6).setMaxWidth(100);
            jTableDefeitos.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTableDefeitos.getColumnModel().getColumn(7).setMaxWidth(100);
            jTableDefeitos.getColumnModel().getColumn(8).setMinWidth(100);
            jTableDefeitos.getColumnModel().getColumn(8).setPreferredWidth(100);
            jTableDefeitos.getColumnModel().getColumn(8).setMaxWidth(100);
            jTableDefeitos.getColumnModel().getColumn(9).setMinWidth(100);
            jTableDefeitos.getColumnModel().getColumn(9).setPreferredWidth(100);
            jTableDefeitos.getColumnModel().getColumn(9).setMaxWidth(100);
            jTableDefeitos.getColumnModel().getColumn(10).setMinWidth(100);
            jTableDefeitos.getColumnModel().getColumn(10).setPreferredWidth(100);
            jTableDefeitos.getColumnModel().getColumn(10).setMaxWidth(100);
        }

        txtPesquisar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyTyped(evt);
            }
        });

        txtCodigoSelecionado.setEnabled(false);
        txtCodigoSelecionado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCodigoSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoSelecionadoActionPerformed(evt);
            }
        });

        txtNomeSelecao.setEnabled(false);
        txtNomeSelecao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        grpOpt.add(optNota);
        optNota.setSelected(true);
        optNota.setText("Notas");
        optNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optNotaActionPerformed(evt);
            }
        });

        grpOpt.add(optPedido);
        optPedido.setText("Pedido");
        optPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optPedidoActionPerformed(evt);
            }
        });

        btnTransportadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page_white_find.png"))); // NOI18N
        btnTransportadora.setText("Transportadora");
        btnTransportadora.setEnabled(false);
        btnTransportadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransportadoraActionPerformed(evt);
            }
        });

        grpOpt.add(optTransportadora);
        optTransportadora.setText("Transportadora");
        optTransportadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optTransportadoraActionPerformed(evt);
            }
        });

        txtFilial.setEnabled(false);
        txtFilial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilialActionPerformed(evt);
            }
        });

        txtEmpresa.setEnabled(false);
        txtEmpresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpresaActionPerformed(evt);
            }
        });

        grpOpt.add(optCli);
        optCli.setText("Nota Nome Cliente");
        optCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCliActionPerformed(evt);
            }
        });

        grpOpt.add(optCli1);
        optCli1.setText("Pedido Nome Cliente");
        optCli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCli1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(optNota, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(optTransportadora, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optCli, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(optPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optCli1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(btnTransportadora))
            .addComponent(txtPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtCodigoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNomeSelecao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(optNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optTransportadora, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(optCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optCli1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCodigoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnTransportadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnTransportadora, optCli, optCli1, optNota, optPedido, optTransportadora});

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page_white_find.png"))); // NOI18N
        btnPesquisar.setText("Confirmar Pesquisa");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Ordens de Compra");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stop.gif"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private String codigoNotaFiscal;
    private String nomeFornecedor;
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if (veioCampo != null) {
            try {
                veioCampo.retornarNotaFiscal(codigoNotaFiscal, txtNomeSelecao.getText(), txtEmpresa.getText(), txtFilial.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Problemas." + ex);
            } finally {
                this.dispose();
            }

        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void jTableDefeitosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDefeitosMouseClicked
        try {
            int linhaSelSit = jTableDefeitos.getSelectedRow();
            int colunaSelSit = jTableDefeitos.getSelectedColumn();
            this.codigoNotaFiscal = jTableDefeitos.getValueAt(linhaSelSit, 1).toString();
            this.nomeFornecedor = jTableDefeitos.getValueAt(linhaSelSit, 2).toString();
            txtCodigoSelecionado.setText(codigoNotaFiscal);
            txtEmpresa.setText(jTableDefeitos.getValueAt(linhaSelSit, 9).toString());
            txtFilial.setText(jTableDefeitos.getValueAt(linhaSelSit, 10).toString());
            //     txtNomeSelecao.setText(nomeFornecedor);
            btnPesquisar.setEnabled(false);

        } catch (Exception ex) {
            Logger.getLogger(IntegrarPedidoVenda.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jTableDefeitosMouseClicked

    private void txtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyPressed
//       try {
//            getListar("TRANSPOTADORA", " and nomtra like '%" + txtPesquisar.getText() + "%'");
//        } catch (Exception ex) {
//            Logger.getLogger(IntegrarNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_txtPesquisarKeyPressed

    private void txtPesquisarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyTyped
//        try {
//            getListar("TRANSPOTADORA", " and nomtra like '%" + txtPesquisar.getText() + "%'");
//        } catch (Exception ex) {
//            Logger.getLogger(IntegrarNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_txtPesquisarKeyTyped

    private String tipoPesquisa;

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed

        if (optNota.isSelected()) {
            try {

                getListar("NFV", " and nfv.numnfv in (" + txtPesquisar.getText() + ")");

            } catch (Exception ex) {
                Logger.getLogger(IntegrarPedidoVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if (optTransportadora.isSelected()) {
            try {

                getListar("NFV", " and nfv.codtra in (" + txtPesquisar.getText() + ")");

            } catch (Exception ex) {
                Logger.getLogger(IntegrarPedidoVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
          if (optCli.isSelected()) {
            try {

                getListar("NFV", " and cli.nomcli like ('%" + txtPesquisar.getText() + "%')");

            } catch (Exception ex) {
                Logger.getLogger(IntegrarPedidoVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void txtCodigoSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoSelecionadoActionPerformed
        //
    }//GEN-LAST:event_txtCodigoSelecionadoActionPerformed

    private void btnTransportadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransportadoraActionPerformed
        try {
            IntegrarTransportadora sol = new IntegrarTransportadora();
            MDIFrame.add(sol, true);
            sol.setMaximum(false); // executa maximizado 
            sol.setSize(800, 500);
            sol.setPosicao();
            sol.setRecebePalavraTransportadora(this);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(IntegrarPesosRegistrar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnTransportadoraActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void optTransportadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optTransportadoraActionPerformed
        btnTransportadora.setEnabled(true);
    }//GEN-LAST:event_optTransportadoraActionPerformed

    private void optPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optPedidoActionPerformed
        btnTransportadora.setEnabled(false);
    }//GEN-LAST:event_optPedidoActionPerformed

    private void optNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optNotaActionPerformed
        btnTransportadora.setEnabled(false);
    }//GEN-LAST:event_optNotaActionPerformed

    private void txtFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilialActionPerformed

    private void txtEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpresaActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        try {
            selecionarRange();
        } catch (Exception ex) {
            Logger.getLogger(IntegrarPedidoVenda.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void optCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optCliActionPerformed

    private void optCli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCli1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optCli1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton btnTransportadora;
    private javax.swing.ButtonGroup grpOpt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDefeitos;
    private javax.swing.JRadioButton optCli;
    private javax.swing.JRadioButton optCli1;
    private javax.swing.JRadioButton optNota;
    private javax.swing.JRadioButton optPedido;
    private javax.swing.JRadioButton optTransportadora;
    private org.openswing.swing.client.TextControl txtCodigoSelecionado;
    private org.openswing.swing.client.TextControl txtEmpresa;
    private org.openswing.swing.client.TextControl txtFilial;
    private org.openswing.swing.client.TextControl txtNomeSelecao;
    private org.openswing.swing.client.TextControl txtPesquisar;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the pessoa
     */
    /**
     * @return the addNewReg
     */
    public boolean isAddNewReg() {
        return addNewReg;
    }

    /**
     * @param addNewReg the addNewReg to set
     */
    public void setAddNewReg(boolean addNewReg) {
        this.addNewReg = addNewReg;
    }

    /**
     * @return the showMsgErros
     */
    public boolean isShowMsgErros() {
        return showMsgErros;
    }

    /**
     * @param showMsgErros the showMsgErros to set
     */
    public void setShowMsgErros(boolean showMsgErros) {
        this.showMsgErros = showMsgErros;
    }
}
